/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHubtelInitiateRouteImport } from './routes/api/public/hubtel/initiate'
import { Route as ApiPublicHubtelCallbackRouteImport } from './routes/api/public/hubtel/callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubtelInitiateRoute = ApiPublicHubtelInitiateRouteImport.update({
  id: '/api/public/hubtel/initiate',
  path: '/api/public/hubtel/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubtelCallbackRoute = ApiPublicHubtelCallbackRouteImport.update({
  id: '/api/public/hubtel/callback',
  path: '/api/public/hubtel/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hubtel/callback': typeof ApiPublicHubtelCallbackRoute
  '/api/public/hubtel/initiate': typeof ApiPublicHubtelInitiateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hubtel/callback': typeof ApiPublicHubtelCallbackRoute
  '/api/public/hubtel/initiate': typeof ApiPublicHubtelInitiateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hubtel/callback': typeof ApiPublicHubtelCallbackRoute
  '/api/public/hubtel/initiate': typeof ApiPublicHubtelInitiateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/programs'
    | '/sitemap.xml'
    | '/api/public/hubtel/callback'
    | '/api/public/hubtel/initiate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/programs'
    | '/sitemap.xml'
    | '/api/public/hubtel/callback'
    | '/api/public/hubtel/initiate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/programs'
    | '/sitemap.xml'
    | '/api/public/hubtel/callback'
    | '/api/public/hubtel/initiate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHubtelCallbackRoute: typeof ApiPublicHubtelCallbackRoute
  ApiPublicHubtelInitiateRoute: typeof ApiPublicHubtelInitiateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hubtel/initiate': {
      id: '/api/public/hubtel/initiate'
      path: '/api/public/hubtel/initiate'
      fullPath: '/api/public/hubtel/initiate'
      preLoaderRoute: typeof ApiPublicHubtelInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hubtel/callback': {
      id: '/api/public/hubtel/callback'
      path: '/api/public/hubtel/callback'
      fullPath: '/api/public/hubtel/callback'
      preLoaderRoute: typeof ApiPublicHubtelCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHubtelCallbackRoute: ApiPublicHubtelCallbackRoute,
  ApiPublicHubtelInitiateRoute: ApiPublicHubtelInitiateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
